language: node_js

cache:
  directories:
    - '$HOME/.sonar/cache'
    
addons:
  sonarcloud:
    organization: 'second-opinion-frontend'
  
node_js:
  - 6
  - 7
  - 8 

before_install:
  - npm install istanbul -g
  - npm install coveralls -g
  - npm install mocha -g

script:
  - npm test

after_success:
  - npm run coveralls
